### ISSUE TITLE
Device offline should not be an error

### ISSUE THREAD

**Issue by gsportelli** [barban-dev/midea_inventor_dehumidifier#10]
When I use the library with my dehumi offline, I get the following error:

    ERROR:root:MideaClient::send_api_request: errorCode=3123, errorMessage="the appliance is off line."

This should not be treated as an error, but as a normal use case, that should be returned to the calling code instead of being logged directly to the user.

**Comment by flyboy013** [comment]
In addition to getting the offline "ERROR", I'm also getting the following traceback in my Home Assistant code.  It would seem that the code should attempt to communicate with an device that is known to be offline.

```
2022-01-27 18:34:26 ERROR (SyncWorker_4) [root] MideaClient::send_api_request: errorCode=3123, errorMessage="The appliance is offline"
2022-01-27 18:34:26 ERROR (MainThread) [homeassistant.helpers.entity] Update for humidifier.midea_dehumidifier_30786325709353 fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/home/homeassistant/.homeassistant/custom_components/midea_dehumidifier/humidifier.py", line 401, in async_update
    res = await self.hass.async_add_executor_job(self._client.get_device_status, self._device['id'])
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 203, in get_device_status
    decodedReplyStr = self.appliance_transparent_send(deviceId, dataStr)
  File "/srv/homeassistant/lib/python3.9/site-packages/midea_inventor_lib/midea_client.py", line 553, in appliance_transparent_send
    if not "reply" in result:
TypeError: argument of type 'NoneType' is not iterable
```
